apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: poc

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 4Gi