apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: gp3
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: ebs.csi.aws.com
parameters:
  fsType: ext4
  type: gp3
deletionPolicy: Delete